#------------------------------------------------------------------------------
# Builds a neonFORGE GitHub repo solution on a JOBRUNNER within the [C:\src] directory.
#
# This currently manages the following neonFORGE repos:
#
#   neonCLOUD           - private/enterprise code including deployment scripts
#   neonKUBE            - public neonKUBE related code
#   neonLIBRARY         - public neonLIBRARY related code
#   cadence-samples     - public Cadence sample apps
#   temporal-samples    - public Temporal sample apps
#
# REMARKS:
#
# This builds all projects in the RELEASE configuration and then builds any additional
# requested artifacts like tools or code documentation.

name: neon-build
description: "Builds one of the neonFORGE repos with options"
inputs:
  repo:
    description: "The repostory to build, one of: neonCLOUD, neonKUBE, neonLIBRARY, cadence-samples, or temporal-samples"
    required: true
  build-tools:
    description: "Indicates whether tools should be built and published to the repo's Build folder"
    required: false
    default: false
  build-installers:
    description: "Indicates whether installers should be built"
    required: false
    default: false
  build-codedoc:
    description: "Indicates whether code documentation should be built"
    required: false
    default: false
  build-log-path:
    description: "Specifies where the build log file should be written"
    required: true
outputs:
  build-error:
    description: "Returns as 'true' for build errors, 'false' otherwise"
runs:
  using: composite
  steps:
  - name: build
    shell: pwsh
    run: |
      
      # Verify that we're running on a properly configured neonFORGE jobrunner 
      # and import the deployment and action scripts from neonCLOUD.
      
      # NOTE: This assumes that the required [$NC_ROOT/Powershell/*.ps1] files
      #       in the current clone of the repo on the runner are up-to-date
      #       enough to be able to obtain secrets and use GitHub Action functions.
      #       If this is not the case, you'll have to manually pull the repo 
      #       first on the runner.
      
      $ncRoot = $env:NC_ROOT
      
      if (![System.IO.Directory]::Exists($ncRoot))
      {
          throw "Runner Config: neonCLOUD repo is not present."
      }
      
      $ncPowershell = [System.IO.Path]::Combine($ncRoot, "Powershell")
      
      Push-Location $ncPowershell
      . ./includes.ps1
      Pop-Location
      
      # Note that each repo has their own build scripts.
      
      $repo         = "${{ inputs.repo }}"
      $buildLog     = "ERROR: Build was never executed."
      $buildError   = $true
      $buildLogPath = "${{ inputs.build-log-path }}"
      
      if ([System.IO.File]::Exists($buildLogPath))
      {
          [System.IO.File]::Delete($buildLogPath)
      }
      
      Switch ($repo)
      {
          ""
          {
              throw "[inputs.repo] is required."
          }
          
          "neonCLOUD"
          {
              $buildScript      = [System.IO.Path]::Combine($env:NC_TOOLBIN, "neoncloud-builder.ps1")
              $toolsOption      = ""
              $installersOption = ""
              $codeDocOption    = ""
              
              if ("${{ inputs.build-tools }}" -eq "true")
              {
                  $toolsOption = "-tools"
              }
              
              if ("${{ inputs.build-installers }}" -eq "true")
              {
                  $installersOption = "-installers"
              }
              
              if ("${{ inputs.build-codedoc }}" -eq "true")
              {
                  # $codeDocOption = "-codedoc"
              }
              
              [System.IO.File]::AppendAllText($buildLogPath, "`r`n")
              [System.IO.File]::AppendAllText($buildLogPath, "==============================`r`n")
              [System.IO.File]::AppendAllText($buildLogPath, "* neonCLOUD`r`n")
              [System.IO.File]::AppendAllText($buildLogPath, "==============================`r`n")
              
              & pwsh $buildScript $toolsOption $installersOption $codeDocOption >> $buildLogPath
              $buildError = $?
              Break
          }
          
          "neonKUBE"
          {
              $buildScript      = [System.IO.Path]::Combine($env:NF_TOOLBIN, "neon-builder.ps1")
              $toolsOption      = ""
              $installersOption = ""
              $codeDocOption    = ""
              
              if ("${{ inputs.build-tools }}" -eq "true")
              {
                  $toolsOption = "-tools"
              }
              
              if ("${{ inputs.build-installer }}" -eq "true")
              {
                  $installersOption = "-installers"
              }
              
              if ("${{ inputs.build-codedoc }}" -eq "true")
              {
                  $codeDocOption = "-codedoc"
              }
              
              [System.IO.File]::AppendAllText($buildLogPath, "`r`n")
              [System.IO.File]::AppendAllText($buildLogPath, "==============================`r`n")
              [System.IO.File]::AppendAllText($buildLogPath, "* neonKUBE`r`n")
              [System.IO.File]::AppendAllText($buildLogPath, "==============================`r`n")
              
              & pwsh $buildScript $toolsOption $installersOption $codeDocOption >> $buildLogPath
              $buildError = $?
              Break
          }
          
          "neonLIBRARY"
          {
              throw "[neonLIBRARY] build is not implemented."
              Break
          }
          
          "cadence-samples"
          {
              throw "[cadence-samples] build is not implemented."
              Break
          }
          
          "temporal-samples"
          {
              throw "[temporal-samples] build is not implemented."
              Break
          }
          
          default
          {
              throw "[$repo] is not a supported repo."
              Break
          }
      }

