#------------------------------------------------------------------------------
# Builds a neonFORGE GitHub repo solution on a JOBRUNNER within the [C:\src] directory.
#
# This currently manages the following neonFORGE repos:
#
#   neonCLOUD           - private/enterprise code including deployment scripts
#   neonKUBE            - public neonKUBE related code
#   neonLIBRARY         - public neonLIBRARY related code
#   cadence-samples     - public Cadence sample apps
#   temporal-samples    - public Temporal sample apps
#
# REMARKS:
#
# This builds all projects in the RELEASE configuration and then builds any additional
# requested artifacts like tools or code documentation.

name: build
description: "Builds one of the neonFORGE repos with options"
inputs:
  repo:
    description: "The repostory to build, one of: neonCLOUD, neonKUBE, neonLIBRARY, cadence-samples, or temporal-samples"
    required: true
  build-tools:
    description: "Indicates whether tools should be built and published to the repo's Build folder"
    required: false
    default: "false"
  build-installers:
    description: "Indicates whether installers should be built"
    required: false
    default: "false"
  build-codedoc:
    description: "Indicates whether code documentation should be built"
    required: false
    default: "false"
  build-log-path:
    description: "Specifies where the build log file should be written"
    required: true
outputs:
  build-error:
    description: "Returns as 'true' for build errors, 'false' otherwise"
runs:
  using: node12
  main: action.js
